version: '3.4'

services:
  snackhub.payment.api:
    image: ${IMAGE}
    build:
      context: .
      dockerfile: src/SnackHub.Payment.Api/Dockerfile
      args:
        PASSWORD_ENV_SEEDED: ${PASSWORD_ENV_SEEDED}
