name: My Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      my_input:
        description: My input parameter
        required: true
        default: teste

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Use Input
        run: echo "The input value is ${{ github.event.inputs.my_input }}"