on: [ push ]
jobs:
  build-and-test:
    uses: Team-One-Pos-Tech/SnackHub.SharedWorkFlows/.github/workflows/build.yml@main
    with:
      solution-name: "SnackHub.PaymentService.sln"
      api-project-name: "SnackHub.PaymentService.Api"
      sonar-project-key: "Team-One-Pos-Tech_SnackHub.Payment"
  
  docker-setup:
    needs: build-and-test
    uses: Team-One-Pos-Tech/SnackHub.SharedWorkFlows/.github/workflows/dockerize.yml@main
    with:
      image-name: "team-one-pos-tech/snack-hub-payment-service"
      api-entrypoint-binary: "SnackHub.PaymentService.Api.dll"