name: Ambiente de Desenvolvimento
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  env:
      PASSWORD_ENV_SEEDED: ${{ secrets.PASSWORD_ENV_SEEDED }}

jobs:
  build-and-test:
    name: "Build docker compose"
    runs-on: [self-hosted, vmbuild]
    steps:
      - uses: actions/checkout@v4

      - name: Build Image
        run: docker compose build