name: Ambiente de Desenvolvimento
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-test:
    name: "Build docker compose"
    runs-on: [self-hosted, vmbuild]
    env:
      PASSWORD_ENV_SEEDED: ${{ secrets.PASSWORD_ENV_SEEDED }}
      IMAGE: "ghcr.io/team-one-pos-tech/snackhubpaymentapi"
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'

      - name: Build Image
        run: docker compose build
      
      - name: Push Image
        run: docker push ${{ env.IMAGE}}

  Deploy:
    name: "Deploy development"
    runs-on: [self-hosted, vmprod]
    needs: build-and-test
    if: github.ref == 'refs/heads/develop'
    env:
      PASSWORD_ENV_SEEDED: ${{ secrets.PASSWORD_ENV_SEEDED }}
      IMAGE: "ghcr.io/team-one-pos-tech/snackhubpaymentapi"
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
      
      - name: Docker pull image
        run: docker pull ${{ env.IMAGE }}

      - name: Execute script de deploy
        run: bash .github/workflows/deploy/deploy.sh --env ${{ env.IMAGE }}
