name: Ambiente de Desenvolvimento
runs-on: self-hosted
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-test:
    name: "Run build and Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore SnackHub.Payment.sln

      - name: Build
        run: dotnet build SnackHub.Payment.sln --no-restore

      - name: Test
        run: dotnet test SnackHub.Payment.sln --no-build --verbosity normal